Development
Vanatel-tech/Identification-Document-Scanning-App pull request #23
Opened 2024-08-08 04:14 UTC by aubreyosenda

[I made sure the profile is working the main activity will be woerking as the home or main window](https://github.com/aubreyosenda/Identification-Document-Scanning-App/pull/2)

2024-08-08 09:46 UTC, Vanatel-tech commented on app/src/main/res/drawable-v24/ic_launcher_foreground.xml
File deleted and needed

2024-08-08 09:56 UTC, Vanatel-tech requested changes
Please review that the code is working as agreed. 

Also your PR has a number of deleted files that will bring up unnecessary errors during testing. An example of the files is the `ic_launcher_background.xml` 

In the PR you submitted, the intent of the `splash screen` goes to the `Login page`. Its should go to the `First page Activity`.

Generally, the files look good especially the profile activity. However you need to set up the correct Intent redirects.

2024-08-09 03:34 UTC, aubreyosenda reviewed
cool

2024-08-09 04:36 UTC, Vanatel-tech approved these changes

2024-08-09 04:36 UTC, merged